project:
  type: book

book:
  title: "Large Language Model tools for R"
  reader-mode: true
  author: "Luis D. Verde Arregoitia"
  date: "February 13 2025"
  chapters:
    - index.qmd
    - before-start.qmd
    - r-pkgs.qmd
    - other-ext.qmd
    - courses.qmd