project:
  type: book
  output-dir: docs

book:
  title: "Large Language Model tools for R"
  reader-mode: true
  author: "Luis D. Verde Arregoitia"
  date: last-modified
  repo-url: https://github.com/luisDVA/llmsr-book
  google-analytics: G-HER1TDPFHR
  chapters:
    - index.qmd
    - before-start.qmd
    - r-pkgs.qmd
    - other-ext.qmd
    - courses.qmd
    - python.qmd
format:
  html:
    theme: [default, indstyle.scss]

babelquarto:
  icon: "bi bi-map"
  languagelinks: sidebar
  languagecodes:
  - name: es
    text: "Español"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['es']
title-es: "Herramientas para usar modelos de lenguaje de gran escala (LLM) en R"
description-es: "IA en R"
author-es: "Luis D. Verde Arregoitia"
lang: en
