# Further reading {#sec-courses}

Here are some courses and guides for actually using the LLM tools listed here. Newest entries at the top, and going forward I will record the date in which I added them.

------------------------------------------------------------------------



## {.unnumbered}


### Are AI Models Hallucinating—Or Just Confabulating? {.unnumbered}

This is a great [read](https://cosimameyer.com/post/are-ai-models-hallucinating-or-just-confabulating/) by Cosima Meyer, breaking down the terminology and nomenclature of _hallucinations_ and whether or not we should be referring to what LLMs do as confabulation instead. Brief but very interesting. Thanks to Simisani Ndaba for bringing this to my attention.
 
### ellmer deep dive (3 part series) {.unnumbered}

This [post](https://www.howardbaik.com/posts/deep-dive-into-ellmer-part3/) by Howard Baik is the latest in a three part series explaining how ellmer works in a practical and accessible description. All three posts are worth catching up on.  

### Programming with LLMs Workshop Materials  {.unnumbered}

Here is the [official page](https://posit-conf-2025.github.io/llm/) with all the code, slides, and materials for the full-day LLM workshop taught during posit::conf 2025 in Atlanta by Garrick Aden-Buie and Joe Cheng. The material includes examples for both R and Python, focused on ellmer and chatlass.  
 
### R-Ladies Gaborone Meetup talk {.unnumbered}

On June 30th, 2025 I joined the monthly meetup organized by R-Ladies Gaborone (Botswana) with a talk about the contents in this book/guide. Thanks for the invitation and to everyone that joined!   Recording and slides below:

[Watch on Youtube](https://youtu.be/0WsF4XcIhYI?si=bh6aBJilhJSFgI5A)

<style>
.slide-deck {
    border: 3px solid #dee2e6;
    width: 100%;
    height: 475px;
}
</style>

<div>
```{=html}
<iframe class="slide-deck" src="/ld-RLadies-slides/slidesLV.html"></iframe>
```
</div>

[View slides in full screen](/ld-RLadies-slides/slidesLV.html)

## {.unnumbered}
 
### Tunis R Users Group Meetup talk {.unnumbered}

On July 31st, 2025 I presented with a talk about the contents in this book/guide. Thanks for the invitation and to everyone that joined! Slides below:

<style>
.slide-deck {
    border: 3px solid #dee2e6;
    width: 100%;
    height: 475px;
}
</style>

<div>
```{=html}
<iframe class="slide-deck" src="/ld-TunisRUG-slides/slidesLV.html"></iframe>
```
</div>


[View slides in full screen](/ld-TunisRUG-slides/slidesLV.html)

## {.unnumbered}

[Harnessing LLMs for Data Analysis](https://www.youtube.com/watch?v=owDd1CJ17uQ)

This ~30 minute demo by Joe Cheng from Posit is a really smooth and easy to follow introduction to calling LLMs via http APIs using code (R or Python). Focuses on ellmer and chatlass. I liked the advice given early on about starting out with the best performing models rather than open-weights local models, and to be very careful about the data we allow these model providers to see. Joe also explained the easiest way to add knowledge to a chat object via the system prompt. A must watch. 

## {.unnumbered}

This [post](https://posit.co/blog/r-llm-evaluation/) by Sara Altman and Simon Couch on the Posit Blog used [vitals](r-pkgs.qmd#vitals) to tackle the question: 

> Which AI model writes the best R code? 

This is not the first such comparison but this one included newer models and considered cost, concluding that for R coding tasks, OpenAI’s o4-mini or Anthropic’s Claude Sonnet 4 will perform quite well. OpenAI’s o3 performed the best on this evaluation, **but is also ten times more expensive than o4-mini and around three times more expensive than Sonnet 4**. These kinds of quantitative evaluations focused on R code are great contributions to this space.  
(**added 03/06/2025**) 

## {.unnumbered}

This post on the official tidyverse blog is well worth reading because it's about [Learning the tidyverse with the help of AI tools](https://www.tidyverse.org/blog/2025/04/learn-tidyverse-ai/#tips-and-good-practices) in the context of the learning process and from the perspective of an experienced instructor. Almost all models nowadays generate working code, but in this post, Mine Çetinkaya-Rundel reviewed the machine-generated code from the perspective of someone who wants to learn.

In summary: code generated by the model sometimes includes unsolicited steps, unnecessary elements, an unhelpful mix of R dialects, and too many code comments. All of this is not very helpful someone who wants to learn to code.  
(**added 04/04/2025**)
  

## { .unnumbered}

This short [tutorial](https://posit.co/blog/mall-ai-powered-text-analysis/) in the officail Posit blog by Camila Lívio demonstrates how to use [mall](r-pkgs.qmd#mall) for text analysis and summarization for context extracted from long and complicated PDF files. 
(**added 02/04/2025**)

## { .unnumbered}

Sharon Machlis at InfoWorld just published a post titled: [GenAI tools for R: New tools to make R programming easier](https://www.infoworld.com/article/3848270/genai-tools-for-r-new-tools-to-make-r-programming-easier.html). The content overlaps with this guide but there are lots of well-explained examples. Worth checking out.  
(**added 26/03/2025**)


## { .unnumbered}

Not a tutorial or course and not necessarily R-related, but I came across this public [list](https://github.com/stars/gadenbuie/lists/ai) of AI-related GitHub repositories compiled by Garrick Aden Buie. If you are familiar with Garrick's work, then you know that at least some of this cool AI stuff will make it onto R packages or extensions in the near future. Worth checking out. 
(**added 24/03/2025**)


## { .unnumbered}

This is way beyond my skillset and experience level, but Javier Orraca-Deatcu recently (07/03/2025) posted "[Vector DB + RAG Maker](https://www.javierorracadeatcu.com/posts/2025-03-07-vector-db-and-rags/)". The post  introduces a "limited vector database and RAG system developed with Python, made for R users, designed to generate bleeding-edge responses from challenging LLM prompts using your local R technical documentation".  Looks fun and promising.   
(**added 18/03/2025**)

## { .unnumbered}

Here's a long-form [video ](https://youtu.be/-YiRWFXNDmk?si=TbSp_HZmwjOHF9aL) of Simon Couch as a guest on the R For the Rest of Us podcast. The interview goes through a lot of relevant AI in R topics, an includes lots of detail on using [chores](r-pkgs.qmd#chores) and [gander](r-pkgs.qmd#gander).   (**added 10/03/2025**)

## { .unnumbered}

This [long-form post](https://drmowinckels.io/blog/2025/ollama/) by Athanasia Mo Mowinckel goes through the setup process and various adventures for using various relevant tools including [ellmer](r-pkgs.qmd#ellmer) [chores](r-pkgs.qmd#chores), [gander](r-pkgs.qmd#gander) and [ensure](r-pkgs.qmd#ensure) with local ollama models for package development. The text shows that the tooling is not quite there yet, but on its way.   
(**added 03/03/2025**)

## { .unnumbered}

David Keyes at R for the Rest of Us recently launched "[Using AI with R](https://rfortherestofus.com/courses/ai)": a free, self-paced short course for using LLM-based assistants with R. Covers many of the tools and packages mentioned on this site.

## { .unnumbered}

Albert Rapp also has an in progress Quarto book "[AI with R](https://air.albert-rapp.de/)", built from his existing blog posts for addressing different tasks using AI tool and not having to work in browser-based chat boxes. This resource includes some very well-written documentation for using mall and ellmer.

## { .unnumbered}

Leonardo Collado Torres gave a short course that covered many of the packages and tools used here, and the recording is available on [YouTube](https://youtu.be/qWuoVQG5BZw?si=YM7Y2s3xfcEd2Sc6). The course materials also include useful step-by-step instructions for setting up and using copilot.


## { .unnumbered}

My fellow UQ alum Chris Brown, now at UTAS, shared this recent entry about [summarizing key details from a methods section](https://www.seascapemodels.org/rstats/2025/02/12/LLMs-for-literature-reviews.html) to assist in literature reviews. The example uses [tidychatmodels](r-pkgs.qmd#tidychatmodels) and I particularly like Chris' advice: **"I’d also recommend you manually check results so that you still learn something yourself"**.

::: {.callout-note}
This post now has a follow-up entry (published 15/03/2025, added here 18/03/2025) which uses [ellmer](r-pkgs.qmd#ellmer) for the same task of literature review. Very detailed step-by-step instruction and a thoughtful discussion at the end. 
:::

## { .unnumbered}

This post by Nic Crane demonstrates how we can use [ellmer](r-pkgs.qmd#ellmer) and Shiny to build an app that [creates posts for different social media platforms](https://niccrane.com/posts/socalmediagen2/).