# Other tools and extensions {#sec-other-ext}

These include vscode/Positron extensions that are not shipped as R packages, as well as relevant web-based resources.


## [Positron Assistant](https://positron.posit.co/assistant)

Positron Assistant is currently a preview/experimental AI client for integrating LLM-based chat and autocomplete within Positron. Available with version >= 2025.07.0-204. At present the assistant supports Anthropic for chat, and GitHub Copilot for code completions. Seems similar to Continue but with a much tighter integration with the IDE. 

## [Roo Code](https://docs.roocode.com/)

Roo Code is another option for running more advanced coding agents in our IDE. We can install Roo Code as an extension in Code OSS forks including Positron, and I've heard some R users have had good experiences with this tool. 

Like other agent tools, Roo Code has different modes for different tasks (ask, code, debug, orchestrate) and each one is highly customizable and designed for coding. I installed the extension in Positron and it looks promising for package development tasks, although like similar tools we need to be aware of the high token use. 

## [Databot](https://positron.posit.co/databot.html)

Databot is an experimental AI assistant for the Positron IDE, designed specifically for exploratory data analysis. Databot needs Positron Assistant enabled to function and thus uses the same LLM provider (Anthropic). Databot can help us explore a dataset and see if there are any issues with the data, any interesting relationships or patterns, and ultimately what questions we could ask and answer. The user is kept in the loop and the exploration is done incrementally, with the assistant suggesting a few options at each step. The team from posit demonstrated Databot during posit::conf 2025 and the whole process looked smooth and useful. 

## [Cursor best practices for R prompt file](https://github.com/PatrickJS/awesome-cursorrules/blob/main/rules/r-cursorrules-prompt-file-best-practices/.cursorrules)

This `.cursorrules` file put together by Ihaddaden Mohamed El Fodil (author of mini007) contains custom rules that Cursor will follow when generating code, and this rules file contains a detailed ruleset optimized for R. Install with the vscode-cursor-rules extension or manually. 

## [GitHub Copilot](https://github.com/features/copilot)

GitHub Copilot is a widely-used and well-documented coding assistant for code completions and the possibility of turning natural language prompts into code suggestions. Works on GitHub.com and inside most IDEs. 

Subscription-based, although as of a a few weeks-ago there is a free tier available. I have not tried it yet.

This recent [talk](https://github.com/yabellini/copilotWithR) by Yanina Bellini for RLadies Rome provides a good overview, and 
Yani's slides also mention important considerations about the AI skill threat. 

## [continue](https://www.continue.dev/)

A vscode extension that works nicely in Positron. Supports multiple models for chat and code completion. Easy to provide local files and folders for context and nice integration with the source editor.

Tried it out after Julia Silge mentioned it in the [Super Data Science](https://www.superdatascience.com/podcast/817) podcast. Works nicely, and I used it in Positron with Anthropic's Claude 3.5 Sonnet model to write and edit the repetitive css, html, and javascript code that powers the hexsession package. Also helped me with some of the nested for loops that play a big role in forgts. 


## [codeium](https://codeium.com/)

Another cool VScode extension that works well in Positron. Provides autocomplete and chat. Free for individuals. The base model uses Llama 3.1 70B, but paid tiers can choose other models. I've tried this out in Positron with good results for code refactoring, at least when playing around with small scripts.


## [R and RStudio Tutor](https://chatgpt.com/g/g-iedyANQtM-r-and-r-studio-tutor)

This is a custom GTP by Jose A. Fernandez Calvo, built on Open AI's framework for custom tutors that have predefined roles and custom knowledge bases. Answers R-related questions and has a system role for being supportive when explaining solutions.

## [RALLY](https://github.com/CodyCarmichaelMPH/RALLY)

RALLY is a programming assistant for R developed by Cody Carmichael. This packages lets us work with local Ollama models running in an interactive Shiny App or as a console-based chat interface. Nice wrapper with well-thought out prompts to work locally and offline. 

--- 

Special mention here for [Shiny Assistant](https://shiny.posit.co/blog/posts/shiny-assistant/), a stand-alone AI tool from the Shiny team that can answer questions about Shiny and also build apps. Shiny assistant works with both R and python, and the tool takes advantage of Shinylive to optionally forego the need for a server running R or python.


Another special mention for [RTutor](https://rtutor.ai/), an early days (~2022) implementation of using ChatGPT to generate R code using natural language. Can be used on the web or locally after installing the RTutor R package.  
