# Otras herramientas o extensiones {#sec-other-ext}

Aquí hay algunas herramientas o extensiones que no se instalan como paquetes R, o que se usan directamente en el navegador.

## [Positron Assistant](https://positron.posit.co/assistant)

Este Asistente de Positron es un cliente de inteligencia artificial experimental para integrar chat y autocompletado basados en LLM dentro de Positron. Está disponible con la versión >=2025.07.0-204. Actualmente, el asistente usa Anthropic para el chat y GitHub Copilot para completar código. Se me hizo muy simlar Continue, pero con una integración mucho más estrecha con el IDE.

## [Roo Code](https://docs.roocode.com/)

Roo Code es otra opción para ejecutar agentes de programación avanzados en nuestro IDE. Podemos instalar Roo Code como una extensión en IDEs derivados de Code OSS, incluyendo Positron. He escuchado que algunos usuarios de R han tenido muy buenas experiencias con esta herramienta.

Al igual que otras herramientas de agentes, Roo Code tiene diferentes modos para distintas tareas (preguntar, programar, depurar, orquestar), y cada uno es altamente personalizable y enfocado en escribir/editar código. Instalé la extensión en Positron y creo que me va a sevir para temas de desarrollo de paquetes, aunque, así con otrasherramientas similares, debemos ser conscientes del alto consumo de tokens.

## [Databot](https://positron.posit.co/databot.html)

Databot es un asistente de inteligencia artificial experimental para el entorno de desarrollo Positron, diseñado específicamente para el análisis exploratorio de datos (EDA por sus siglas en inglés). Databot requiere que el Asistente de Positron esté activado para funcionar, por lo que utiliza el mismo proveedor de modelos que por ahora es únicamente Anthropic. Databot puede ayudarnos a explorar un conjunto de datos y detectar posibles problemas, relaciones o patrones interesantes, así como identificar preguntas que podríamos formular y responder. El usuario se mantiene informado en todo momento y la exploración se realiza de forma incremental, con sugerencias del asistente en cada paso. El equipo de Posit demostró Databot durante posit::conf 2025, y el proceso me pareció fluido y útil.

## [Reglas sobre R para Cursor](https://github.com/PatrickJS/awesome-cursorrules/blob/main/rules/r-cursorrules-prompt-file-best-practices/.cursorrules)

Este archivo `.cursorrules`, elaborado por Ihaddaden Mohamed El Fodil (autor de mini007), contiene reglas personalizadas que Cursor va a ir siguiendo mientras genera código de R. Este archivo de reglas incluye un conjunto detallado de reglas y bunas prácticas, optimizado para R. Para instalarlo, se puede usar la extensión vscode-cursor-rules o cargar de forma manual.

## [GitHub Copilot](https://github.com/features/copilot)

Copilot es un asistente de programación bien documentado, usado ampliamente desde hace unos años, y bastante versátil. Sirve para autocompletar nuestros códigos de programación o también para responder preguntas y dar sugerencias. Funciona en el sitio de GitHub y dentro de casi todos los IDEs.

Copilot es un servicio de paga aunque recientemente ya tiene una cuenta gratuita que sigo sin probar.

Podemos aprender más viendo esta  [presentación](https://github.com/yabellini/copilotWithR) que dio Yanina Bellini para el grupo de RLadies Roma. 

## [continue](https://www.continue.dev/)

Continue es una extensión para vscode pero que funciona bien en Positron. Tiene soporte para casi todos los modelos que hay y nos da chat, autocompletado de código, y tiene un herramienta para ir aplicando los cambios sugeridos a nuestros archivos. Es fácil mencionar archivos y carpetas para dar contexto y la integración con el editor me gustó mucho.

Es la primera extensión que usé después de esuchar que Julia Silge la mencionara en el podcast [Super Data Science](https://www.superdatascience.com/podcast/817). 
Me ha funcionado muy bien con Claude y diferentes modelos de groQ, y de hecho usé la extensión y éstos modelos para editar el código de css, html y javascript que usa mi paquete hexsession.


## [codeium](https://codeium.com/)

Codeium es otra extensión para vscode que funciona bien en Positron. También nos ayuda a autocompletar código y nos brinda un chat parecido al de Continue. Tiene un plan gratuito y otros planes de paga con acceso a más modelos. El plan gratuito usa el modelo Llama 3.170B.


## [R and RStudio Tutor](https://chatgpt.com/g/g-iedyANQtM-r-and-r-studio-tutor)

Yo no sabía pero es posible construir GTPs personalizados encima de modelos de openAI y que éstos vivan en línea en el entorno de chatGPT. R and RStudio tutor,  por Jose A. Fernandez Calvo, es un tutor específicamente diseñado para enseñar y explicar sobre R.

> Mención especial para [RTutor](https://rtutor.ai/), que fue una de las primeras herramientas (~2022) para usar ChatGPT y generar código a partir de lenguaje natural. Se puede usar en línea o localmente instalándolo a tráves de su propio paquete.  

## [RALLY](https://github.com/CodyCarmichaelMPH/RALLY)

RALLY es un asistente de programación para R desarrollado por Cody Carmichael. Este paquete nos permite trabajar con modelos locales de Ollama que corren y se accedend mediante una aplicación de Shiny interactiva, o como una interfaz de chat en la consola. Buena opción para trabajar localmente y sin conexión a internet. 


## [Shiny Assistant](https://shiny.posit.co/blog/posts/shiny-assistant/)

También hay que mencionar a Shiny Assistant. Esta herramienta la desarrolló el equipo de Shiny y puede contestar preguntas sobre Shiny o de plano construir y editar aplicaciones. Funciona para R y para Python, y puede usar Shinylive para prescindir de un servidor.

